import {NextRequest, NextResponse} from 'next/server'
import prisma from 'src/lib/prisma'

// import prisma from 'src/lib/prisma'

// 勘定科目マスタデータ（CSVから抽出）
const accountMasterData = [
  // 現金及び預金
  {
    category: '貸借対照表',
    classification: '現金及び預金',
    balanceSheet: '現金',
    account: '現金',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 1,
  },
  {
    category: '貸借対照表',
    classification: '現金及び預金',
    balanceSheet: '現金',
    account: '現金',
    subAccount: '小口現金',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 2,
  },
  {
    category: '貸借対照表',
    classification: '現金及び預金',
    balanceSheet: '当座預金',
    account: '当座預金',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 3,
  },
  {
    category: '貸借対照表',
    classification: '現金及び預金',
    balanceSheet: '普通預金',
    account: '普通預金',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 4,
  },

  // 経費関連（よく使用される項目）
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '租税公課',
    account: '租税公課',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 100,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '荷造運賃',
    account: '荷造運賃',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 101,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '水道光熱費',
    account: '水道光熱費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 102,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '旅費交通費',
    account: '旅費交通費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 103,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '旅費交通費',
    account: '旅費交通費',
    subAccount: 'ガソリン代',
    taxCategory: '課仕 10%',
    searchKey: 'gas',
    isActive: true,
    sortOrder: 104,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '通信費',
    account: '通信費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 105,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '広告宣伝費',
    account: '広告宣伝費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 106,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '接待交際費',
    account: '接待交際費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 107,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '接待交際費',
    account: '接待交際費',
    subAccount: '飲食費',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 108,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '損害保険料',
    account: '損害保険料',
    subAccount: '',
    taxCategory: '非仕',
    searchKey: '',
    isActive: true,
    sortOrder: 109,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '修繕費',
    account: '修繕費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 110,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '消耗品費',
    account: '消耗品費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 111,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '減価償却費',
    account: '減価償却費',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 112,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '福利厚生費',
    account: '福利厚生費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 113,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '給料賃金',
    account: '給料賃金',
    subAccount: '',
    taxCategory: '対象外仕',
    searchKey: '',
    isActive: true,
    sortOrder: 114,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '外注工賃',
    account: '外注工賃',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 115,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '利子割引料',
    account: '利子割引料',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 116,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '地代家賃',
    account: '地代家賃',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 117,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '地代家賃',
    account: '地代家賃',
    subAccount: '駐車場代',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 118,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '車両費',
    account: '車両費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 119,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '車両費',
    account: '車両費',
    subAccount: 'ガソリン代',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 120,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: 'リース料',
    account: 'リース料',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 121,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '支払手数料',
    account: '支払手数料',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 122,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '研修採用費',
    account: '研修採用費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 123,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '新聞図書費',
    account: '新聞図書費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 124,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '会議費',
    account: '会議費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 125,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '雑費',
    account: '雑費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 126,
  },
]

// 科目選択肢マスタデータ
const subjectOptions = [
  {
    category: 'subjects',
    value: 'entertainment',
    label: '接待交際費',
    description: '取引先との飲食・接待費用',
    isActive: true,
    sortOrder: 1,
    color: '#FF6B6B',
  },
  {
    category: 'subjects',
    value: 'travel',
    label: '旅費交通費',
    description: '出張・移動に関する費用',
    isActive: true,
    sortOrder: 2,
    color: '#4ECDC4',
  },
  {
    category: 'subjects',
    value: 'communication',
    label: '通信費',
    description: '電話・インターネット・郵送費',
    isActive: true,
    sortOrder: 3,
    color: '#45B7D1',
  },
  {
    category: 'subjects',
    value: 'supplies',
    label: '消耗品費',
    description: '事務用品・消耗品',
    isActive: true,
    sortOrder: 4,
    color: '#96CEB4',
  },
  {
    category: 'subjects',
    value: 'advertising',
    label: '広告宣伝費',
    description: '広告・宣伝・マーケティング費用',
    isActive: true,
    sortOrder: 5,
    color: '#FFEAA7',
  },
  {
    category: 'subjects',
    value: 'meeting',
    label: '会議費',
    description: '会議・打ち合わせ費用',
    isActive: true,
    sortOrder: 6,
    color: '#DDA0DD',
  },
  {
    category: 'subjects',
    value: 'training',
    label: '研修採用費',
    description: '研修・セミナー・採用費用',
    isActive: true,
    sortOrder: 7,
    color: '#98D8C8',
  },
  {
    category: 'subjects',
    value: 'books',
    label: '新聞図書費',
    description: '書籍・雑誌・新聞代',
    isActive: true,
    sortOrder: 8,
    color: '#F7DC6F',
  },
  {
    category: 'subjects',
    value: 'rent',
    label: '地代家賃',
    description: '事務所・駐車場賃料',
    isActive: true,
    sortOrder: 9,
    color: '#BB8FCE',
  },
  {
    category: 'subjects',
    value: 'utilities',
    label: '水道光熱費',
    description: '電気・ガス・水道代',
    isActive: true,
    sortOrder: 10,
    color: '#85C1E9',
  },
  {
    category: 'subjects',
    value: 'vehicle',
    label: '車両費',
    description: '車両関連費用',
    isActive: true,
    sortOrder: 11,
    color: '#F8C471',
  },
  {
    category: 'subjects',
    value: 'outsourcing',
    label: '外注工賃',
    description: '外部委託費用',
    isActive: true,
    sortOrder: 12,
    color: '#82E0AA',
  },
  {
    category: 'subjects',
    value: 'welfare',
    label: '福利厚生費',
    description: '従業員福利厚生',
    isActive: true,
    sortOrder: 13,
    color: '#F1948A',
  },
  {
    category: 'subjects',
    value: 'maintenance',
    label: '修繕費',
    description: '設備・機器の修理費',
    isActive: true,
    sortOrder: 14,
    color: '#D7BDE2',
  },
  {
    category: 'subjects',
    value: 'fees',
    label: '支払手数料',
    description: '各種手数料',
    isActive: true,
    sortOrder: 15,
    color: '#A9DFBF',
  },
  {
    category: 'subjects',
    value: 'misc',
    label: '雑費',
    description: 'その他の費用',
    isActive: true,
    sortOrder: 16,
    color: '#D5DBDB',
  },
]

// 業種選択肢マスタデータ
const industryOptions = [
  {
    category: 'industries',
    value: 'it_software',
    label: 'IT・ソフトウェア',
    description: 'システム開発・IT関連',
    isActive: true,
    sortOrder: 1,
    color: '#3498DB',
  },
  {
    category: 'industries',
    value: 'web_design',
    label: 'Web・デザイン',
    description: 'Webサイト制作・デザイン',
    isActive: true,
    sortOrder: 2,
    color: '#E74C3C',
  },
  {
    category: 'industries',
    value: 'consulting',
    label: 'コンサルティング',
    description: '経営・業務コンサルティング',
    isActive: true,
    sortOrder: 3,
    color: '#2ECC71',
  },
  {
    category: 'industries',
    value: 'marketing',
    label: 'マーケティング・広告',
    description: '広告代理店・マーケティング',
    isActive: true,
    sortOrder: 4,
    color: '#F39C12',
  },
  {
    category: 'industries',
    value: 'finance',
    label: '金融・保険',
    description: '銀行・証券・保険',
    isActive: true,
    sortOrder: 5,
    color: '#9B59B6',
  },
  {
    category: 'industries',
    value: 'manufacturing',
    label: '製造業',
    description: '製品製造・工場',
    isActive: true,
    sortOrder: 6,
    color: '#34495E',
  },
  {
    category: 'industries',
    value: 'retail',
    label: '小売・卸売',
    description: '商品販売・流通',
    isActive: true,
    sortOrder: 7,
    color: '#16A085',
  },
  {
    category: 'industries',
    value: 'real_estate',
    label: '不動産',
    description: '不動産売買・賃貸',
    isActive: true,
    sortOrder: 8,
    color: '#E67E22',
  },
  {
    category: 'industries',
    value: 'construction',
    label: '建設・建築',
    description: '建設工事・建築設計',
    isActive: true,
    sortOrder: 9,
    color: '#95A5A6',
  },
  {
    category: 'industries',
    value: 'healthcare',
    label: '医療・介護',
    description: '病院・クリニック・介護',
    isActive: true,
    sortOrder: 10,
    color: '#E91E63',
  },
  {
    category: 'industries',
    value: 'education',
    label: '教育・研修',
    description: '学校・塾・研修機関',
    isActive: true,
    sortOrder: 11,
    color: '#673AB7',
  },
  {
    category: 'industries',
    value: 'logistics',
    label: '物流・運輸',
    description: '運送・配送・倉庫',
    isActive: true,
    sortOrder: 12,
    color: '#607D8B',
  },
  {
    category: 'industries',
    value: 'food_beverage',
    label: '飲食・食品',
    description: 'レストラン・食品製造',
    isActive: true,
    sortOrder: 13,
    color: '#FF5722',
  },
  {
    category: 'industries',
    value: 'entertainment',
    label: 'エンターテイメント',
    description: '映像・音楽・ゲーム',
    isActive: true,
    sortOrder: 14,
    color: '#FF9800',
  },
  {
    category: 'industries',
    value: 'travel_hotel',
    label: '旅行・ホテル',
    description: '旅行代理店・宿泊業',
    isActive: true,
    sortOrder: 15,
    color: '#00BCD4',
  },
  {
    category: 'industries',
    value: 'government',
    label: '官公庁・自治体',
    description: '行政機関・公的機関',
    isActive: true,
    sortOrder: 16,
    color: '#795548',
  },
  {
    category: 'industries',
    value: 'npo',
    label: 'NPO・NGO',
    description: '非営利団体',
    isActive: true,
    sortOrder: 17,
    color: '#4CAF50',
  },
  {
    category: 'industries',
    value: 'other',
    label: 'その他',
    description: 'その他の業種',
    isActive: true,
    sortOrder: 18,
    color: '#9E9E9E',
  },
]

// 目的選択肢マスタデータ
const purposeOptions = [
  {
    category: 'purposes',
    value: 'new_business',
    label: '新規事業開拓',
    description: '新しいビジネス機会の探索',
    isActive: true,
    sortOrder: 1,
    color: '#FF6B6B',
  },
  {
    category: 'purposes',
    value: 'existing_business',
    label: '既存事業拡大',
    description: '現在の事業の拡張・強化',
    isActive: true,
    sortOrder: 2,
    color: '#4ECDC4',
  },
  {
    category: 'purposes',
    value: 'partnership',
    label: 'パートナーシップ',
    description: '業務提携・協業の検討',
    isActive: true,
    sortOrder: 3,
    color: '#45B7D1',
  },
  {
    category: 'purposes',
    value: 'technology_exchange',
    label: '技術情報交換',
    description: '技術的な知見・情報の共有',
    isActive: true,
    sortOrder: 4,
    color: '#96CEB4',
  },
  {
    category: 'purposes',
    value: 'market_research',
    label: '市場調査',
    description: '市場動向・競合分析',
    isActive: true,
    sortOrder: 5,
    color: '#FFEAA7',
  },
  {
    category: 'purposes',
    value: 'customer_support',
    label: '顧客サポート',
    description: '既存顧客への支援・相談',
    isActive: true,
    sortOrder: 6,
    color: '#DDA0DD',
  },
  {
    category: 'purposes',
    value: 'problem_solving',
    label: '課題解決',
    description: '具体的な問題の解決策検討',
    isActive: true,
    sortOrder: 7,
    color: '#98D8C8',
  },
  {
    category: 'purposes',
    value: 'networking',
    label: 'ネットワーキング',
    description: '人脈構築・関係性強化',
    isActive: true,
    sortOrder: 8,
    color: '#F7DC6F',
  },
  {
    category: 'purposes',
    value: 'learning',
    label: '学習・研修',
    description: 'スキルアップ・知識習得',
    isActive: true,
    sortOrder: 9,
    color: '#BB8FCE',
  },
  {
    category: 'purposes',
    value: 'recruitment',
    label: '採用・人材',
    description: '人材採用・人事関連',
    isActive: true,
    sortOrder: 10,
    color: '#85C1E9',
  },
  {
    category: 'purposes',
    value: 'investment',
    label: '投資・資金調達',
    description: '投資機会・資金調達の検討',
    isActive: true,
    sortOrder: 11,
    color: '#F8C471',
  },
  {
    category: 'purposes',
    value: 'compliance',
    label: 'コンプライアンス',
    description: '法的・規制対応',
    isActive: true,
    sortOrder: 12,
    color: '#82E0AA',
  },
  {
    category: 'purposes',
    value: 'maintenance',
    label: 'メンテナンス',
    description: '既存システム・設備の保守',
    isActive: true,
    sortOrder: 13,
    color: '#F1948A',
  },
  {
    category: 'purposes',
    value: 'social',
    label: '社交・親睦',
    description: '関係維持・親睦深化',
    isActive: true,
    sortOrder: 14,
    color: '#D7BDE2',
  },
  {
    category: 'purposes',
    value: 'other',
    label: 'その他',
    description: 'その他の目的',
    isActive: true,
    sortOrder: 15,
    color: '#D5DBDB',
  },
]

export async function POST(request: NextRequest) {
  try {
    const {type} = await request.json()

    if (type === 'accounts' || type === 'all') {
      // 勘定科目マスタのシード
      console.log('勘定科目マスタをシード中...')

      // 既存データを削除
      await prisma.keihiAccountMaster.deleteMany({})

      // 新しいデータを挿入
      await prisma.keihiAccountMaster.createMany({
        data: accountMasterData,
      })

      console.log(`勘定科目マスタ ${accountMasterData.length} 件をシードしました`)
    }

    if (type === 'options' || type === 'all') {
      // 選択肢マスタのシード
      console.log('選択肢マスタをシード中...')

      // 既存データを削除
      await prisma.keihiOptionMaster.deleteMany({})

      // 科目選択肢を挿入
      await prisma.keihiOptionMaster.createMany({
        data: subjectOptions,
      })

      // 業種選択肢を挿入
      await prisma.keihiOptionMaster.createMany({
        data: industryOptions,
      })

      // 目的選択肢を挿入
      await prisma.keihiOptionMaster.createMany({
        data: purposeOptions,
      })

      console.log(`選択肢マスタ ${subjectOptions.length + industryOptions.length + purposeOptions.length} 件をシードしました`)
    }

    return NextResponse.json({
      success: true,
      message: 'マスターデータのシードが完了しました',
      counts: {
        accounts: type === 'accounts' || type === 'all' ? accountMasterData.length : 0,
        subjects: type === 'options' || type === 'all' ? subjectOptions.length : 0,
        industries: type === 'options' || type === 'all' ? industryOptions.length : 0,
        purposes: type === 'options' || type === 'all' ? purposeOptions.length : 0,
      },
    })
  } catch (error) {
    console.error('シードエラー:', error)
    return NextResponse.json(
      {
        success: false,
        error: 'マスターデータのシードに失敗しました',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      {status: 500}
    )
  }
}

export async function GET() {
  try {
    // 現在のマスターデータ件数を取得
    const accountCount = await prisma.keihiAccountMaster.count()
    const subjectCount = await prisma.keihiOptionMaster.count({
      where: {category: 'subjects'},
    })
    const industryCount = await prisma.keihiOptionMaster.count({
      where: {category: 'industries'},
    })
    const purposeCount = await prisma.keihiOptionMaster.count({
      where: {category: 'purposes'},
    })

    return NextResponse.json({
      success: true,
      currentCounts: {
        accounts: accountCount,
        subjects: subjectCount,
        industries: industryCount,
        purposes: purposeCount,
      },
      seedDataCounts: {
        accounts: accountMasterData.length,
        subjects: subjectOptions.length,
        industries: industryOptions.length,
        purposes: purposeOptions.length,
      },
    })
  } catch (error) {
    console.error('マスターデータ取得エラー:', error)
    return NextResponse.json(
      {
        success: false,
        error: 'マスターデータの取得に失敗しました',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      {status: 500}
    )
  }
}
