import {NextRequest, NextResponse} from 'next/server'

import prisma from 'src/lib/prisma'

// CSVファイルから抽出した完全な勘定科目マスタデータ
const fullAccountMasterData = [
  // 貸借対照表 - 現金及び預金
  {
    category: '貸借対照表',
    classification: '現金及び預金',
    balanceSheet: '現金',
    account: '現金',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 1,
  },
  {
    category: '貸借対照表',
    classification: '現金及び預金',
    balanceSheet: '現金',
    account: '現金',
    subAccount: '小口現金',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 2,
  },
  {
    category: '貸借対照表',
    classification: '現金及び預金',
    balanceSheet: '当座預金',
    account: '当座預金',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 3,
  },
  {
    category: '貸借対照表',
    classification: '現金及び預金',
    balanceSheet: '普通預金',
    account: '普通預金',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 4,
  },
  {
    category: '貸借対照表',
    classification: '現金及び預金',
    balanceSheet: '定期預金',
    account: '定期預金',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 5,
  },
  {
    category: '貸借対照表',
    classification: '現金及び預金',
    balanceSheet: 'その他の預金',
    account: 'その他の預金',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 6,
  },

  // 貸借対照表 - 売上債権
  {
    category: '貸借対照表',
    classification: '売上債権',
    balanceSheet: '受取手形',
    account: '受取手形',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 10,
  },
  {
    category: '貸借対照表',
    classification: '売上債権',
    balanceSheet: '売掛金',
    account: '売掛金',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 11,
  },

  // 貸借対照表 - 有価証券
  {
    category: '貸借対照表',
    classification: '有価証券',
    balanceSheet: '有価証券',
    account: '有価証券',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 15,
  },

  // 貸借対照表 - 棚卸資産
  {
    category: '貸借対照表',
    classification: '棚卸資産',
    balanceSheet: '棚卸資産',
    account: '商品',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 20,
  },
  {
    category: '貸借対照表',
    classification: '棚卸資産',
    balanceSheet: '棚卸資産',
    account: '貯蔵品',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 21,
  },
  {
    category: '貸借対照表',
    classification: '棚卸資産',
    balanceSheet: '棚卸資産',
    account: '材料',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 22,
  },
  {
    category: '貸借対照表',
    classification: '棚卸資産',
    balanceSheet: '棚卸資産',
    account: '仕掛品',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 23,
  },
  {
    category: '貸借対照表',
    classification: '棚卸資産',
    balanceSheet: '棚卸資産',
    account: '製品',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 24,
  },

  // 貸借対照表 - その他流動資産
  {
    category: '貸借対照表',
    classification: 'その他流動資産',
    balanceSheet: '未収賃貸料',
    account: '未収賃貸料',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 30,
  },
  {
    category: '貸借対照表',
    classification: 'その他流動資産',
    balanceSheet: '前払金',
    account: '前払金',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 31,
  },
  {
    category: '貸借対照表',
    classification: 'その他流動資産',
    balanceSheet: '貸付金',
    account: '貸付金',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 32,
  },
  {
    category: '貸借対照表',
    classification: 'その他流動資産',
    balanceSheet: '立替金',
    account: '立替金',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 33,
  },
  {
    category: '貸借対照表',
    classification: 'その他流動資産',
    balanceSheet: '未収金',
    account: '未収金',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 34,
  },
  {
    category: '貸借対照表',
    classification: 'その他流動資産',
    balanceSheet: '仮払金',
    account: '仮払金',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 35,
  },
  {
    category: '貸借対照表',
    classification: 'その他流動資産',
    balanceSheet: '仮払消費税等',
    account: '仮払消費税',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 36,
  },

  // 損益計算書 - 売上（収入）金額
  {
    category: '損益計算書',
    classification: '売上（収入）金額',
    balanceSheet: '売上（収入）金額',
    account: '売上高',
    subAccount: '',
    taxCategory: '課売 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 100,
  },
  {
    category: '損益計算書',
    classification: '売上（収入）金額',
    balanceSheet: '売上（収入）金額',
    account: '売上値引・返品',
    subAccount: '',
    taxCategory: '課売-返還 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 101,
  },
  {
    category: '損益計算書',
    classification: '売上（収入）金額',
    balanceSheet: '売上（収入）金額',
    account: '家事消費等',
    subAccount: '',
    taxCategory: '課売 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 102,
  },
  {
    category: '損益計算書',
    classification: '売上（収入）金額',
    balanceSheet: '売上（収入）金額',
    account: '雑収入',
    subAccount: '',
    taxCategory: '課売 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 103,
  },

  // 損益計算書 - 期首商品（製品）棚卸高
  {
    category: '損益計算書',
    classification: '期首商品（製品）棚卸高',
    balanceSheet: '期首商品（製品）棚卸高',
    account: '期首商品棚卸高',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 105,
  },

  // 損益計算書 - 当期仕入高
  {
    category: '損益計算書',
    classification: '当期仕入高',
    balanceSheet: '仕入金額',
    account: '仕入高',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 110,
  },
  {
    category: '損益計算書',
    classification: '当期仕入高',
    balanceSheet: '仕入金額',
    account: '仕入値引・返品',
    subAccount: '',
    taxCategory: '課仕-返還 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 111,
  },

  // 損益計算書 - 期末商品（製品）棚卸高
  {
    category: '損益計算書',
    classification: '期末商品（製品）棚卸高',
    balanceSheet: '期末商品（製品）棚卸高',
    account: '期末商品棚卸高',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 115,
  },

  // 損益計算書 - 経費（よく使用される項目）
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '租税公課',
    account: '租税公課',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 120,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '荷造運賃',
    account: '荷造運賃',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 121,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '水道光熱費',
    account: '水道光熱費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 122,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '旅費交通費',
    account: '旅費交通費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 123,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '旅費交通費',
    account: '旅費交通費',
    subAccount: '通勤手当',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 124,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '旅費交通費',
    account: '旅費交通費',
    subAccount: 'ガソリン代',
    taxCategory: '課仕 10%',
    searchKey: 'gas',
    isActive: true,
    sortOrder: 125,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '通信費',
    account: '通信費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 126,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '広告宣伝費',
    account: '広告宣伝費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 127,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '接待交際費',
    account: '接待交際費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 128,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '接待交際費',
    account: '接待交際費',
    subAccount: '飲食費',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 129,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '損害保険料',
    account: '損害保険料',
    subAccount: '',
    taxCategory: '非仕',
    searchKey: '',
    isActive: true,
    sortOrder: 130,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '損害保険料',
    account: '損害保険料',
    subAccount: '地震保険・火災保険',
    taxCategory: '非仕',
    searchKey: '',
    isActive: true,
    sortOrder: 131,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '修繕費',
    account: '修繕費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 132,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '消耗品費',
    account: '消耗品費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 133,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '減価償却費',
    account: '減価償却費',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 134,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '福利厚生費',
    account: '福利厚生費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 135,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '福利厚生費',
    account: '法定福利費',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 136,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '給料賃金',
    account: '給料賃金',
    subAccount: '',
    taxCategory: '対象外仕',
    searchKey: '',
    isActive: true,
    sortOrder: 137,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '給料賃金',
    account: '給料賃金',
    subAccount: '住宅手当',
    taxCategory: '対象外仕',
    searchKey: '',
    isActive: true,
    sortOrder: 138,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '給料賃金',
    account: '給料賃金',
    subAccount: '残業手当',
    taxCategory: '対象外仕',
    searchKey: '',
    isActive: true,
    sortOrder: 139,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '給料賃金',
    account: '退職給与',
    subAccount: '',
    taxCategory: '対象外仕',
    searchKey: '',
    isActive: true,
    sortOrder: 140,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '外注工賃',
    account: '外注工賃',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 141,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '利子割引料',
    account: '利子割引料',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 142,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '地代家賃',
    account: '地代家賃',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 143,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '地代家賃',
    account: '地代家賃',
    subAccount: '駐車場代',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 144,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '貸倒金',
    account: '貸倒金(損失)',
    subAccount: '',
    taxCategory: '課売-貸倒 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 145,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '車両費',
    account: '車両費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 146,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '車両費',
    account: '車両費',
    subAccount: 'ガソリン代',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 147,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '車両費',
    account: '車両費',
    subAccount: '損害保険',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 148,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '車両費',
    account: '車両費',
    subAccount: '点検・車検',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 149,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: 'リース料',
    account: 'リース料',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 150,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '支払手数料',
    account: '支払手数料',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 151,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '研修採用費',
    account: '研修採用費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 152,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '新聞図書費',
    account: '新聞図書費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 153,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '会議費',
    account: '会議費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 154,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '繰延資産償却',
    account: '繰延資産償却',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 155,
  },
  {
    category: '損益計算書',
    classification: '経費',
    balanceSheet: '雑費',
    account: '雑費',
    subAccount: '',
    taxCategory: '課仕 10%',
    searchKey: '',
    isActive: true,
    sortOrder: 156,
  },

  // 損益計算書 - 繰戻額等
  {
    category: '損益計算書',
    classification: '繰戻額等',
    balanceSheet: '貸倒引当金戻入',
    account: '貸倒引当金戻入',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 160,
  },

  // 損益計算書 - 繰入額等
  {
    category: '損益計算書',
    classification: '繰入額等',
    balanceSheet: '専従者給与',
    account: '専従者給与',
    subAccount: '',
    taxCategory: '対象外仕',
    searchKey: '',
    isActive: true,
    sortOrder: 165,
  },
  {
    category: '損益計算書',
    classification: '繰入額等',
    balanceSheet: '貸倒引当金繰入',
    account: '貸倒引当金繰入',
    subAccount: '',
    taxCategory: '対象外',
    searchKey: '',
    isActive: true,
    sortOrder: 166,
  },
]

export async function POST(request: NextRequest) {
  try {
    console.log('完全版勘定科目マスタをシード中...')

    // 既存データを削除
    await prisma.keihiAccountMaster.deleteMany({})

    // 新しいデータを挿入
    await prisma.keihiAccountMaster.createMany({
      data: fullAccountMasterData,
    })

    console.log(`完全版勘定科目マスタ ${fullAccountMasterData.length} 件をシードしました`)

    return NextResponse.json({
      success: true,
      message: '完全版勘定科目マスタのシードが完了しました',
      count: fullAccountMasterData.length,
      categories: {
        貸借対照表: fullAccountMasterData.filter(item => item.category === '貸借対照表').length,
        損益計算書: fullAccountMasterData.filter(item => item.category === '損益計算書').length,
      },
    })
  } catch (error) {
    console.error('完全版シードエラー:', error)
    return NextResponse.json(
      {
        success: false,
        error: '完全版勘定科目マスタのシードに失敗しました',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      {status: 500}
    )
  }
}

export async function GET() {
  try {
    // 現在のマスターデータ件数を取得
    const accountCount = await prisma.keihiAccountMaster.count()
    const categoryBreakdown = await prisma.keihiAccountMaster.groupBy({
      by: ['category'],
      _count: {
        id: true,
      },
    })

    return NextResponse.json({
      success: true,
      currentCount: accountCount,
      categoryBreakdown: categoryBreakdown.reduce(
        (acc, item) => {
          acc[item.category] = item._count.id
          return acc
        },
        {} as Record<string, number>
      ),
      seedDataCount: fullAccountMasterData.length,
      seedCategoryBreakdown: {
        貸借対照表: fullAccountMasterData.filter(item => item.category === '貸借対照表').length,
        損益計算書: fullAccountMasterData.filter(item => item.category === '損益計算書').length,
      },
    })
  } catch (error) {
    console.error('完全版マスターデータ取得エラー:', error)
    return NextResponse.json(
      {
        success: false,
        error: '完全版マスターデータの取得に失敗しました',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      {status: 500}
    )
  }
}
